# Generated by Django 6.0.7 on 2026-08-02 16:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('interviews', '0001_initial'),
        ('resumes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CodingQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('difficulty', models.CharField(choices=[('EASY', 'Easy'), ('MEDIUM', 'Medium'), ('HARD', 'Hard')], max_length=20)),
                ('programming_language', models.CharField(choices=[('PYTHON', 'Python'), ('JAVA', 'Java'), ('JAVASCRIPT', 'JavaScript'), ('CPP', 'C++'), ('C', 'C'), ('CSHARP', 'C#')], max_length=20)),
                ('problem_statement', models.TextField()),
                ('input_format', models.TextField(blank=True)),
                ('output_format', models.TextField(blank=True)),
                ('constraints', models.TextField(blank=True)),
                ('sample_input', models.TextField(blank=True)),
                ('sample_output', models.TextField(blank=True)),
                ('explanation', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('skill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coding_questions', to='resumes.skill')),
            ],
        ),
        migrations.CreateModel(
            name='CodingSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('programming_language', models.CharField(choices=[('PYTHON', 'Python'), ('JAVA', 'Java'), ('JAVASCRIPT', 'JavaScript'), ('CPP', 'C++'), ('C', 'C'), ('CSHARP', 'C#')], max_length=20)),
                ('source_code', models.TextField()),
                ('execution_output', models.TextField(blank=True)),
                ('execution_time', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('memory_used', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('test_cases_passed', models.PositiveIntegerField(default=0)),
                ('total_test_cases', models.PositiveIntegerField(default=0)),
                ('score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('ai_feedback', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('PASSED', 'Passed'), ('FAILED', 'Failed')], max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('interview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coding_submissions', to='interviews.interview')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='coding.codingquestion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coding_submissions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
